/*
 This file is part of HTML Directory List Generator.

 HTML Directory List Generator is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

 HTML Directory List Generator is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

 You should have received a copy of the GNU General Public License along with HTML Directory List Generator. If not, see <https://www.gnu.org/licenses/>.
 */

using System.Reflection;

namespace HDLG_winforms
{
	/// <summary>
	/// Centralizes HDLG application branding assets and HTML export markup.
	/// </summary>
	public static class AppBranding
	{
		public const string AccentColorHex = "#0284C8";

		private const string InlineLogoSvg =
			"<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 320 160\" role=\"img\" aria-label=\"HDLG\">" +
			"<g fill=\"#0284C8\">" +
			"<rect x=\"24\" y=\"24\" width=\"10\" height=\"52\" rx=\"2\"/>" +
			"<rect x=\"58\" y=\"24\" width=\"10\" height=\"52\" rx=\"2\"/>" +
			"<rect x=\"24\" y=\"45\" width=\"44\" height=\"10\" rx=\"2\"/>" +
			"<rect x=\"186\" y=\"24\" width=\"10\" height=\"52\" rx=\"2\"/>" +
			"<path d=\"M196 24 H220 Q252 24 252 50 Q252 76 220 76 H196 Z M206 34 H218 Q238 34 238 50 Q238 66 218 66 H206 Z\" fill-rule=\"evenodd\"/>" +
			"<rect x=\"24\" y=\"96\" width=\"10\" height=\"52\" rx=\"2\"/>" +
			"<rect x=\"24\" y=\"138\" width=\"44\" height=\"10\" rx=\"2\"/>" +
			"<path d=\"M186 96 H218 Q252 96 252 122 Q252 148 218 148 H186 V138 H218 Q236 138 236 122 Q236 106 218 106 H186 V96 Z M228 122 H252 V132 H228 Z\"/>" +
			"</g></svg>";

		/// <summary>
		/// Self-contained inline SVG logo used in HTML exports.
		/// </summary>
		public static string InlineLogoSvgMarkup => InlineLogoSvg;

		/// <summary>
		/// Returns the HTML footer markup for generated directory listings.
		/// </summary>
		public static string GetHtmlFooterMarkup (string? version)
		{
			string safeVersion = System.Net.WebUtility.HtmlEncode( version ?? string.Empty );
			return
				"<footer class=\"hdlg-footer\">" +
				$"<span class=\"hdlg-footer-logo\" aria-hidden=\"true\">{InlineLogoSvgMarkup}</span>" +
				$"<span class=\"hdlg-footer-text\">Generated by <strong>HTML Directory List Generator</strong>{(string.IsNullOrEmpty( safeVersion ) ? string.Empty : $" {safeVersion}")}</span>" +
				"</footer>";
		}

		/// <summary>
		/// Loads the application icon from the packaged multi-size ICO asset.
		/// </summary>
		public static Icon LoadApplicationIcon ()
		{
			string iconPath = Path.Combine( GetAssetsDirectory( ), "hdlg-icon.ico" );
			if (System.IO.File.Exists( iconPath ))
			{
				return new Icon( iconPath );
			}

			return AppLogoRenderer.CreateApplicationIcon( );
		}

		/// <summary>
		/// Loads the Inkscape-rendered wordmark used in the About dialog.
		/// </summary>
		public static Image LoadLogoImage ()
		{
			string logoPath = Path.Combine( GetAssetsDirectory( ), "hdlg-logo.png" );
			if (System.IO.File.Exists( logoPath ))
			{
				return Image.FromFile( logoPath );
			}

			return AppLogoRenderer.RenderWordmark( 640, 320 );
		}

		private static string GetAssetsDirectory ()
		{
			string? assemblyDirectory = Path.GetDirectoryName( Assembly.GetExecutingAssembly( ).Location );
			ArgumentException.ThrowIfNullOrWhiteSpace( assemblyDirectory );
			return Path.Combine( assemblyDirectory, "Assets" );
		}
	}
}